# version: "3.7"

x-default-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

x-common-labels: &default-labels
  logging: "promtail"
  logging_jobname: "containerlogs"
  stackname: "docker-monitoring-stack-gpnc"

services:
  certbot:
    image: openmrs/openmrs-reference-application-3-certbot:${TAG:-qa}
    container_name: certbot
    environment:
      CERT_WEB_DOMAINS: ${CERT_WEB_DOMAINS:-localhost,127.0.0.1}  # Set your domains here, first entry will be common name
      CERTBOT_DATA_PATH: ${CERTBOT_DATA_PATH:-/var/www/certbot}  # Set the path for certbot data
      CERT_ROOT_PATH: ${CERT_ROOT_PATH:-/etc/letsencrypt}  # Set the path for certificates
      CERT_RSA_KEY_SIZE: ${CERT_RSA_KEY_SIZE:-4096}  # Set the RSA key size for the certificate
      CERT_CONTACT_EMAIL: ${CERT_CONTACT_EMAIL:-}  # Set your email for Let's Encrypt notifications
    volumes:
      - letsencrypt-data:/etc/letsencrypt
      - certbot-data:/var/www/certbot
    cpus: 0.5
    mem_limit: 512m
    labels:
      <<: *default-labels
    logging: *default-logging

  gateway:
    image: openmrs/openmrs-reference-application-3-gateway:${TAG:-qa}
    container_name: gateway
    restart: "unless-stopped"
    depends_on:
      - frontend
      - backend
    environment:
      CERT_WEB_DOMAIN_COMMON_NAME: ${CERT_WEB_DOMAIN_COMMON_NAME:-localhost}  # Set your domain here
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverse-proxy_public
      - public
    volumes:
      - letsencrypt-data:/etc/letsencrypt:ro
      - certbot-data:/var/www/certbot
    cpus: 0.5
    mem_limit: 512m
    labels:
      <<: *default-labels
    logging: *default-logging

  frontend:
    image: openmrs/openmrs-reference-application-3-frontend:${TAG:-qa}
    container_name: openmrs-frontend
    restart: "unless-stopped"
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS: /openmrs/spa/config-core_demo.json
      SPA_DEFAULT_LOCALE:
    networks:
      - reverse-proxy_public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
    depends_on:
      - backend
    cpus: 0.5
    mem_limit: 512m
    labels:
      <<: *default-labels
    logging: *default-logging

  backend:
    image: openmrs/openmrs-reference-application-3-backend:${TAG:-qa}
    container_name: openmrs-backend
    restart: "unless-stopped"
    depends_on:
      - db
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: ${OMRS_DB_USER:-openmrs}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
    networks:
      - reverse-proxy_public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data
    cpus: 0.5
    mem_limit: 512m
    labels:
      <<: *default-labels
    logging: *default-logging

  # MariaDB
  db:
    image: mariadb:10.11.7
    container_name: openmrs-db
    restart: "unless-stopped"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
    healthcheck:
      test: "mysql --user=${OMRS_DB_USER:-openmrs} --password=${OMRS_DB_PASSWORD:-openmrs} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OMRS_DB_USER:-openmrs}
      MYSQL_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-openmrs}
    volumes:
      - db-data:/var/lib/mysql
    cpus: 0.5
    mem_limit: 512m
    labels:
      <<: *default-labels
    logging: *default-logging

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.0.0}
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-grafanaAdmin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-grafanaAdminPassword}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL:-https://localhost/grafana}
      GF_USERS_DEFAULT_THEME: dark
      GF_LOG_MODE: console
      GF_LOG_LEVEL: critical
      GF_PANELS_ENABLE_ALPHA: true
      GF_FEATURE_TOGGLES_ENABLE: accessControlOnCall lokiLogsDataplane
      GF_INSTALL_PLUGINS: grafana-polystat-panel
    volumes:
      - ./monitoring/configs/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./monitoring/configs/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
      - ./monitoring/dashboards/node-metrics.json:/var/lib/grafana/dashboards/node-metrics.json:ro
      - ./monitoring/dashboards/host-docker-merged-metrics.json:/var/lib/grafana/dashboards/host-docker-merged-metrics.json:ro
      - ./monitoring/dashboards/container-metrics.json:/var/lib/grafana/dashboards/container-metrics.json:ro
      - ./monitoring/dashboards/log-search.json:/var/lib/grafana/dashboards/log-search.json:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    # ports:
    #   - 3000:3000
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
      - reverse-proxy_public
    labels:
      <<: *default-labels
    logging: *default-logging

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.42.0}
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=error'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://localhost:9090'
    volumes:
      - ./monitoring/configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/configs/prometheus/recording-rules.yml:/etc/prometheus/recording-rules.yml
      - ./monitoring/configs/prometheus/alerting-rules.yml:/etc/prometheus/alerting-rules.yml
      - prometheus-data:/prometheus
    depends_on:
      - alertmanager
    # ports:
    #   - 9090:9090
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
      - reverse-proxy_public
    labels:
      <<: *default-labels
    logging: *default-logging

  telegraf:
    image: telegraf:${TELEGRAF_VERSION:-1.31.3}
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./monitoring/configs/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # ports:
    #   - 9273:9273
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
      - reverse-proxy_public
    labels:
      <<: *default-labels
    logging: *default-logging

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION:-v0.46.0}
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
        # https://github.com/google/cadvisor/issues/1565#issuecomment-718812180
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/disk:/dev/disk:ro
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
    labels:
      <<: *default-labels
    logging: *default-logging

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:-v1.5.0}
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
      - reverse-proxy_public
    labels:
      <<: *default-labels
    logging: *default-logging

  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_VERSION:-v0.25.0}
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--log.level=error'
      - '--storage.path=/alertmanager'
      - '--web.external-url=https://localhost/alertmanager'
    volumes:
      - ./monitoring/configs/alertmanager/alertmanager-fallback-config.yml:/etc/alertmanager/config.yml
    # ports:
    #   - 9093:9093
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
      - reverse-proxy_public
    depends_on:
      - uncomplicated-alert-receiver
    labels:
      <<: *default-labels
    logging: *default-logging

  uncomplicated-alert-receiver:
    image: ghcr.io/jamesread/uncomplicated-alert-receiver:1.2.2
    container_name: uncomplicated-alert-receiver
    restart: unless-stopped
    environment:
      ALERTMANAGER_HOST: https://localhost/alertmanager
    ports:
      - 9094:8080
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
      - reverse-proxy_public
    labels:
      <<: *default-labels
    logging: *default-logging

  redis:
    image: redis:${REDIS_VERSION:-6}
    container_name: redis
    # ports:
    #   - 6379:6379
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
      - reverse-proxy_public
    labels:
      <<: *default-labels
    logging: *default-logging

  loki:
    image: grafana/loki:3.3.2
    container_name: loki
    user: root
    # ports:
    #   - 3100:3100
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./monitoring/configs/loki/loki.yaml:/etc/loki/loki.yaml
      - ./monitoring/configs/loki/rules.yaml:/etc/loki/rules/fake/loki-rules.yml
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
      - reverse-proxy_public
    labels:
      <<: *default-labels
    logging: *default-logging

  promtail:
    image:  grafana/promtail:3.3.2
    container_name: promtail
    volumes:
      - ./monitoring/configs/promtail/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    cpus: 0.5
    mem_limit: 512m
    networks:
      - monitoring
    labels:
      <<: *default-labels
    logging: *default-logging

volumes:
  openmrs-data: ~
  db-data: ~
  letsencrypt-data: ~
  certbot-data: ~ 
  grafana-data: ~
  prometheus-data: ~

networks:
  public:
    name: public
  reverse-proxy_public:
    name: reverse-proxy_public
  monitoring:
    name: monitoring