{
 "title": "Host System and Docker Container Metrics",
 "description": "This dashboard provides a unified view of both host system and Docker container metrics. Use this dashboard to monitor and analyze overall system health and container performance in one place.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Overall Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(__name__) (system_n_cpus)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg by(__name__) (mem_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(cpu) (cpu_usage_active{cpu=\"cpu-total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(host) (mem_used_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_n_containers_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Containers Stopped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_n_containers_stopped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU (Container)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(container_name) (docker_container_cpu_usage_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (Container)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(container_name) (docker_container_mem_usage_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Core execution / min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(cpu) (rate(cpu_time_active{cpu!=\"cpu-total\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(avg by(host) (mem_used), \"host\", \"Used\", \"host\", \".*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(avg by(host) (mem_buffered), \"host\", \"Buffer\", \"host\", \".*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(avg by(host) (mem_cached), \"host\", \"Cache\", \"host\", \".*\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Byets Recevied / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(interface) (rate(net_bytes_recv[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes Sent / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(interface) (rate(net_bytes_sent[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read-Write Bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(name) (rate(diskio_write_bytes{name=~\"[^l].*[^0-9]\"}[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "- avg by(name) (rate(diskio_read_bytes{name=~\"[^l].*[^0-9]\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Docker Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Throttling Rate (ns/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns/s" } },
   "targets": [
    {
     "expr": "avg by(container_name) (rate(docker_container_cpu_throttling_throttled_time[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processes Memory Consumed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(container_name) (docker_container_mem_active_anon)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(container_name) (rate(docker_container_net_rx_bytes[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(container_name) (rate(docker_container_net_tx_bytes[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(container_name) (rate(docker_container_blkio_io_service_bytes_recursive_read[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write Bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(container_name) (rate(docker_container_blkio_io_service_bytes_recursive_write[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by(container_image, container_status, container_version, container_name) (docker_container_status_uptime_ns)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}